### ISSUE TITLE
Support for other lisps

### ISSUE THREAD

**Issue by ToucheSir** [bhurlow/vim-parinfer#10]
Currently, vim-parinfer will simply ignore any file without a .clj\* extension. This rules out using the parinfer for clojure-esque lisps such as [mal](https://github.com/kanaka/mal). Ideally, it should be possible to either call a registration function to add different file extensions or call some of the hooks vim-parinfer uses internally to set up the functionality.

**Comment by bhurlow** [comment]
other lisps should definitely be supported. Some of this depends on how parinfer works – I think it should work with almost all s-expression based languages. 

Maybe it makes sense to adjust the [autocommands](https://github.com/bhurlow/vim-parinfer/blob/master/plugin/parinfer.vim#L190-L198) to simply call something like *.clj,*.cljs,*.mal etc. 

Since parinfer is sort of lisp agnostic though, it'd also be nice to allow the user to define if their language is lisp-like

**Comment by bhurlow** [comment]
maybe its possible to set something like: `g:parinfer_lisp_files = *.mal, *.lisp, *.clj`

**Comment by shaunlebron** [comment]
my goal is to make parinfer work with all Lisps, if possible.  it's working well for both Clojure and Racket so far.  let me know if there are problems for other lisps!

**Comment by bhurlow** [comment]
cool! good to know

**Comment by bhurlow** [comment]
we should be able to just add as many file extension matches as needed
